name: Create Platform Infra tag

on:
  push:
    branches: 
      - "main" 
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  
  create:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: fetch all tags
        run: git fetch --tags origin

      - name: Calculate next version
        id: semver
        run: |
          version_prefix="platform/infra"
          
          latest_version=`git tag --sort=committerdate -l | grep ^$tag_prefix | tail -1`
          echo "Latest version is ${latest_version}"
          
          new_version=`echo ${latest_version} | awk -F. '{print $1 "." $2 "." $3+1}'`
          echo "New version is ${new_version}"
          
          # Pass version to next step
          echo "new_version=${new_version}" >> "$GITHUB_OUTPUT"

      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ steps.semver.outputs.new_version}}',
              sha: context.sha
            })
