name: Create Platform Infra tag

on:
  push:
    branches: 
      - "main" 
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  
  create:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Increment tag (patch)
        id: platform_tag
        run: |
          git fetch --tags origin
          current_tag=`git tag --sort=committerdate -l | grep platform/infra/v1 | tail -1`
          echo "Current tag is ${current_tag}"
          new_tag=`echo ${current_tag} | awk -F. '{print $1 "." $2 "." $3+1}'`
          echo "new tag is ${new_tag}"
          echo "new=${new_tag}" >> "$GITHUB_OUTPUT"

      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ steps.platform_tag.outputs.new}}',
              sha: context.sha
            })
