name: Create Platform Infra tag

on:
  push:
    branches: 
      - "main" 
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  
  create:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          prefix: platform/infra
      
      - name: 'Get next minor version'
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}

      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ steps.semvers.outputs.v_patch}}',
              sha: context.sha
            })
